version: "3"

services:
  ms-user:
    build:
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    container_name: mongodb
    restart: on-failure
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: mongo-db
    volumes:
      - dbuser:/data/dbuser/

volumes:
  dbuser: