name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
       
     - name: Setup JDK 17
       uses: actions/setup-java@v2
       with:
         distribution: 'temurin'
         java-version: '17'
       
     - name: commande random 
       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

     - name: package ms-user
       run: cd ./Back-Flag-User-Service && mvn package
       
     - name: package ms-countries
       run: cd ./countries-service && mvn package
       
     - name: Build ms-user
       run: docker build "${{ github.workspace }}/Back-Flag-User-Service" -t ms-user:latest

     - name: Build ms-countries
       run: docker build "${{ github.workspace }}/countries-service" -t ms-countries:latest

     - name: Build front
       run: docker build "${{ github.workspace }}/Front-Flag/" -t front:latest

     - name: Push ms-user
       run: docker push ms-user:latest

     - name: Push ms-countries
       run: docker push ms-countries:latest

     - name: Push front
       run: docker push front:latest
