name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout Repository
       uses: actions/checkout@v2
       
     - name: commande random 
       run: echo ${{github.workspace}}

     - name: Build & Push ms-user
       run: docker build "${{ github.workspace }}/Back-Flag-User-Service" -t ms-user:latest

     - name: Build & Push ms-countries
       run: docker build "${{ github.workspace }}/countries-service" -t ms-countries:latest

     - name: Build & Push front
       run: docker build "${{ github.workspace }}/Front-Flag/" -t front:latest
